name: 'Helm GCS Publish'
description: 'Published helm charts to GCS'
inputs:
  role-name: 
    description: 'we want to publish or validate charts'
    required: true
  chart-path:
    description: 'Path to helm chart directory'
    required: true
    default: './helm'
  helm-gcs-repository: # Replaces $HELM_GCS_REPOSITORY env var. Assumes only one or other is set
    description: 'Helm repository GCS URL'
    required: false
  helm-gcs-credentials: # Replaces $HELM_GCS_CREDENTIALS env var. Assumes only one or other is set
    description: 'Credentials for writing to Helm repository'
    required: false
runs:
  using: 'docker'
  image: '../dockerfile'
  args: 
    - ${{ inputs.role-name }}
    - ${{ inputs.chart-path }}
