name: Validate GitHub Actions Workflows

on:
  push:
  pull_request:
  # See: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout local repository
        uses: actions/checkout@v2

      - name: Install JSON schema validator
        run: npm install --global ajv-cli@4.0.1

      # See: https://github.com/ajv-validator/ajv-cli/blob/master/README.md
      - name: Validate GitHub Actions workflows
        run: |
          ajv -s "./.github/schemas/github-action.json" -d "**/*.{yml,yaml}"
